version: "3.9"

services:
  discord-line-bridge:
    build: .
    container_name: discord-line-bridge
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LINE_TOKEN=${LINE_TOKEN}
      - LINE_USER_ID=${LINE_USER_ID}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
